# Generated by Django 3.2 on 2021-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
